### ISSUE TITLE
lsx-comp not installed

### ISSUE THREAD

**Issue by Aditi138** [apertium/apertium-eng-deu#7]
Hello,

I am trying to get the eng-deu working. However when running the ./configure in the apertium-eng-deu dir I am getting the error:  You don't have lsx-comp installed. 

Additionally, the README mentions that we need to have apertium-eng and apertium-deu softwares installed. But in the wikipedia they mention that in the language directories we shouldn't be running ./autogen.sh as things would get messy. Because when I tried compiling the 'apertium-eng' and 'apertium-deu' dir I got the same message that './configure: line 2761: AP_MKINCLUDE: command not found' despite the configure.ac having it already included.

Could you please help?

From https://wiki.apertium.org/wiki/Installation_troubleshooting: 
'First off, make sure you've run ./autogen.sh in both the monolingual packages and the language pair. This typically fixes it.

Don't run ./configure in apertium language data; the autogen.sh file is a wrapper around configure that sets up various paths and such before running configure for you.

(Those paths aren't so important if you installed apertium from the nightly apt-get repos, but if you installed apertium from source or something other than apt-get, then running ./configure will probably mess things up unless you also make sure you've exported PKG_CONFIG_PATH and ACLOCAL_PATH to the right directories. Probably safest just to run ./autogen.sh in apertium data directories.)

'

**Comment by nlhowell** [comment]
Aditi - notifications@github.com wrote:
> Hello,
> 
> I am trying to get the eng-deu working. However when running the
> ./configure in the apertium-eng-deu dir I am getting the error: You
> don't have lsx-comp installed.

You must install apertium-separable to get this.

**Comment by khannatanmai** [comment]
@Aditi138 the ``lsx-comp`` program comes from the apertium-separable package: https://github.com/apertium/apertium-separable

**Comment by TinoDidriksen** [comment]
What OS / distro are you on? There are binary packages for many, so you don't have to build from source. You can get better help on IRC Freenode #apertium

**Comment by Aditi138** [comment]
Thanks a lot everyone, installing that package solved all issues!
