### ISSUE TITLE
IRSTLM installation for gcc 7+

### ISSUE THREAD

**Issue by Aditi138** [apertium/apertium-eng-deu#8]
Hello, 

To learn the lexical rules from parallel corpora we need to install IRSTLM. However, I am facing the following issue on gcc 7+:

``` [  2%] Building CXX object src/CMakeFiles/irstlm.dir/dictionary.cpp.o
In file included from /usr/include/c++/7/ext/string_conversions.h:41:0,
                 from /usr/include/c++/7/bits/basic_string.h:6361,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/iomanip:40,
                 from /irstlm/src/dictionary.cpp:25:
/usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
src/CMakeFiles/irstlm.dir/build.make:88: recipe for target 'src/CMakeFiles/irstlm.dir/dictionary.cpp.o' failed
make[2]: *** [src/CMakeFiles/irstlm.dir/dictionary.cpp.o] Error 1
CMakeFiles/Makefile2:341: recipe for target 'src/CMakeFiles/irstlm.dir/all' failed
make[1]: *** [src/CMakeFiles/irstlm.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
``` 

On searching  I found this fix https://github.com/kaldi-asr/kaldi/issues/1588 however its not working. Any ideas?

**Comment by nlhowell** [comment]
Aditi - notifications@github.com wrote:
> Hello, 
> 
> To learn the lexical rules from parallel corpora we need to install
> IRSTLM. However, I am facing the following issue on gcc 7+:
> 
> ``` [  2%] Building CXX object src/CMakeFiles/irstlm.dir/dictionary.cpp.o
> In file included from /usr/include/c++/7/ext/string_conversions.h:41:0,
>                  from /usr/include/c++/7/bits/basic_string.h:6361,
>                  from /usr/include/c++/7/string:52,
>                  from /usr/include/c++/7/bits/locale_classes.h:40,
>                  from /usr/include/c++/7/bits/ios_base.h:41,
>                  from /usr/include/c++/7/iomanip:40,
>                  from /usr2/home/aschaudh/mt-lexical/irstlm/src/dictionary.cpp:25:
> /usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
>  #include_next <stdlib.h>
>                ^~~~~~~~~~
> compilation terminated.
> src/CMakeFiles/irstlm.dir/build.make:88: recipe for target 'src/CMakeFiles/irstlm.dir/dictionary.cpp.o' failed
> make[2]: *** [src/CMakeFiles/irstlm.dir/dictionary.cpp.o] Error 1
> CMakeFiles/Makefile2:341: recipe for target 'src/CMakeFiles/irstlm.dir/all' failed
> make[1]: *** [src/CMakeFiles/irstlm.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
> ``` 
> 
> On searching I found this fix https://github.com/kaldi-
> asr/kaldi/issues/1588 however its not working. Any ideas?

This doesn't seem to be an issue with apertium-eng-deu; if you don't
want to talk to the developers of IRSTLM, you could try asking on IRC:
webchat.freenode.net, channel #apertium.
